// Code generated by Slice Machine. DO NOT EDIT.

import ImageLeftContentRight from './ImageLeftContentRight';
import NavigationItem from './NavigationItem';
import TextSlice from './TextSlice';

export {
	ImageLeftContentRight,
	NavigationItem,
	TextSlice,
};

export const components = {
	image_left_content_right: ImageLeftContentRight,
	navigation: NavigationItem,
	text_slice: TextSlice,
};
